;===================================================================================================
; Assembly Utilities Library
;
; Written By: Oded Cnaan (oded.8bit@gmail.com)
; Site: http://odedc.net 
; Licence: GPLv3 (see LICENSE file)
; Package: UtilLib
;
; Description: 
; Include this file to get access to the utilities library
;===================================================================================================

; Common definitions
TRUE        equ     1
FALSE       equ     0
NULL        equ     0

; Includes
include GrLib\UtilLib\util.asm
include GrLib\UtilLib\string.asm
include GrLib\UtilLib\math.asm
include GrLib\UtilLib\file.asm
include GrLib\UtilLib\print.asm
include GrLib\UtilLib\sound.asm
include GrLib\UtilLib\time.asm
include GrLib\UtilLib\keys.asm
include GrLib\UtilLib\mouse.asm
include GrLib\UtilLib\mem.asm
